### ISSUE TITLE
一个程序设计缺陷的备忘

### ISSUE THREAD

**Issue by Khihz9th** [Khihz9th/plusAndMins#2]
在二维数组一个位置存储一个信息的设计下，采用了入口和出口随机在地图上进行移动的方式来生成通关的正确路径，在这种方法下，目前已知的缺陷备忘（也是日后升级的重点）

*  ~未考虑两条路径自旋导致无法相遇的情况。~
（目前在积极的改进中）
* 自旋的解决方案
* 游戏的输出

后续如果有其他发现的缺陷，也会积极在这个进行同步的

**Comment by shucreater** [comment]
it cannot work ,still

**Comment by Khihz9th** [comment]
> it cannot work ,still

使用dev c++编译main.c文件试一试。
